version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel

    nginx:
        image: nginx:alpine
        container_name: laravel_nginx
        ports:
            - "8080:80"
        volumes:
            - ./public:/var/www/public
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - app
        networks:
            - laravel

    db:
        image: mysql:5.7
        container_name: laravel_mysql
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: task_lara
            MYSQL_USER: tasker
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge
